// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package talos

// NonEmptyString is a required string value that must not be empty.
type NonEmptyString string

// HTTPURL is an HTTP or HTTPS URL.
type HTTPURL string

// RelativePath is a repository- or config-relative path.
type RelativePath string

// ArtifactName is a local artifact filename, not a path.
type ArtifactName string

// SchematicID is an Image Factory schematic ID.
type SchematicID string

// TalosVersion selects an exact Talos Linux release.
type TalosVersion string

// Architecture selects the Talos image architecture.
type Architecture string

// Platform selects the Talos image platform.
type Platform string

// SourceArtifact selects the Image Factory artifact to download.
type SourceArtifact string

// OutputFormat selects the local artifact format produced by the build.
type OutputFormat string

// ConfigDelivery selects how the Talos machine configuration is delivered.
type ConfigDelivery string

// DNSLabel is a single RFC 1123-style hostname label.
type DNSLabel string

// FileInput points at a local file consumed by the build.
type FileInput struct {
	// Path is a relative path from the build config directory.
	Path RelativePath `json:"path"`
}

// ImageSource describes the Talos Image Factory asset to download.
type ImageSource struct {
	// FactoryURL is the Image Factory base URL.
	FactoryURL string `json:"factoryURL"`

	// Version is the exact Talos Linux release to download.
	Version TalosVersion `json:"version"`

	// SchematicID identifies the Image Factory schematic.
	SchematicID string `json:"schematicID"`

	// Platform selects the Talos platform image.
	Platform Platform `json:"platform"`

	// Arch selects the Talos image architecture.
	Arch Architecture `json:"arch"`

	// Artifact selects the compressed Image Factory disk artifact.
	Artifact SourceArtifact `json:"artifact"`
}

// NoCloudMetaData describes the meta-data file in the NoCloud cidata image.
type NoCloudMetaData struct {
	// LocalHostname is the VM hostname advertised through NoCloud.
	LocalHostname DNSLabel `json:"localHostname"`

	// InstanceID identifies this NoCloud instance. It defaults to localHostname.
	InstanceID string `json:"instanceID"`
}

// MachineConfig describes Talos machine configuration delivery.
type MachineConfig struct {
	// Delivery controls how config files are packaged for Talos.
	Delivery ConfigDelivery `json:"delivery"`

	// UserData is the Talos machine config written as NoCloud user-data.
	UserData FileInput `json:"userData"`

	// MetaData is the NoCloud meta-data payload.
	MetaData NoCloudMetaData `json:"metaData"`

	// NetworkConfig optionally points at a NoCloud network-config file.
	NetworkConfig FileInput `json:"networkConfig,omitempty"`
}

// ImageOutput describes the local artifacts produced by the build.
type ImageOutput struct {
	// Dir is the output directory for generated artifacts.
	Dir NonEmptyString `json:"dir"`

	// Format is the local artifact format.
	Format OutputFormat `json:"format"`

	// BootArtifactName is the Talos boot disk IMG filename.
	BootArtifactName ArtifactName `json:"bootArtifactName"`

	// ConfigArtifactName is the NoCloud cidata IMG filename.
	ConfigArtifactName ArtifactName `json:"configArtifactName"`
}

// ImageBuild is the top-level Talos image download and config packaging contract.
type ImageBuild struct {
	// Name is the stable build name used in logs and generated metadata.
	Name NonEmptyString `json:"name"`

	// Source describes the upstream Talos image to download.
	Source ImageSource `json:"source"`

	// Config describes Talos machine configuration delivery.
	Config MachineConfig `json:"config"`

	// Output describes the local artifacts produced by the build.
	Output ImageOutput `json:"output"`
}
