// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package incusos

type NonEmptyString string

type HTTPURL string

type ImageFormat string

type ImageVersion string

type ImageSize string

type SeedOffset int64

type SecretRef struct {
	Path NonEmptyString `json:"path"`

	Field NonEmptyString `json:"field"`
}

type SecretString struct {
	SecretRef SecretRef `json:"secretRef"`
}

type ImageSource struct {
	IndexURL HTTPURL `json:"indexURL"`

	BaseURL HTTPURL `json:"baseURL"`

	Channel string `json:"channel"`

	Arch string `json:"arch"`

	Version ImageVersion `json:"version"`
}

type ImageOutput struct {
	Dir NonEmptyString `json:"dir"`

	ArtifactName NonEmptyString `json:"artifactName"`

	Size ImageSize `json:"size"`

	Format string `json:"format"`
}

type Application struct {
	Name NonEmptyString `json:"name"`
}

type ApplicationsSeed struct {
	Version string `json:"version"`

	Applications []Application `json:"applications"`
}

type TrustedClientCertificate struct {
	Name NonEmptyString `json:"name"`

	Type string `json:"type"`

	Certificate SecretString `json:"certificate"`
}

type IncusPreseed struct {
	Config map[string]string `json:"config,omitempty"`

	Certificates []TrustedClientCertificate `json:"certificates"`
}

type IncusSeed struct {
	Version string `json:"version"`

	ApplyDefaults bool `json:"apply_defaults"`

	Preseed IncusPreseed `json:"preseed"`
}

type Seed struct {
	Offset SeedOffset `json:"offset"`

	Applications ApplicationsSeed `json:"applications"`

	Incus IncusSeed `json:"incus"`
}

type ImageBuild struct {
	Name NonEmptyString `json:"name"`

	Source ImageSource `json:"source"`

	Output ImageOutput `json:"output"`

	Seed Seed `json:"seed"`
}
